# Generated by Django 5.0.1 on 2024-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
